all:

	ghdl -a 0_pc.vhd
	ghdl -a 1_somador.vhd
	ghdl -a 2_pc_forward.vhd
	ghdl -a 3_rom.vhd
	ghdl -a 4_pc_rom.vhd
	ghdl -a 5_maquina_de_estados.vhd
	ghdl -a 6_un_ctrl.vhd
	ghdl -a 7_maior.vhd
	ghdl -a 8_menor.vhd
	ghdl -a 9_mux16bits.vhd
	ghdl -a 10_soma.vhd
	ghdl -a 11_subtr.vhd
	ghdl -a 12_ula.vhd
	ghdl -a 13_reg16bits.vhd
	ghdl -a 14_mux16bits_8x3x1.vhd
	ghdl -a 15_decoder_3x8.vhd
	ghdl -a 16_banco_de_registradores.vhd
	ghdl -a 17_mux_2x1.vhd
	ghdl -a 18_ula_e_banco.vhd
	ghdl -a processador.vhd

rm:

	*.ghw
	*.cf